---
driver:
  name: digitalocean
  flavor: "512MB"
  require_chef_omnibus: latest
busser:
  sudo: false
platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: debian-7.0
  run_list:
  - recipe[apt]
suites:
- name: default
  run_list:
  - recipe[puma-test]
  - recipe[minitest-handler]
  attributes:
