---
driver_plugin: digitalocean
driver_config:
  flavor_id: 66
  require_chef_omnibus: latest

platforms:
- name: debian-7.0
- name: ubuntu-13.10

suites:
- name: default
  run_list:
  - recipe[puma-test]
- name: puma-rails
  run_list:
    - recipe[puma-test::rails]
- name: phased-restarts
  run_list:
    - recipe[puma-test::phased_restarts]
